### ISSUE TITLE
exit status1 when generating

### ISSUE THREAD

**Issue by huglester** [benschw/satis-go#2]
Hello,

I get this when adding repos:

```
$ ./satis-go 
2015/11/20 17:07:35 Generating...
2015/11/20 17:07:35 exit status 1
2015/11/20 17:07:35 Generating...
2015/11/20 17:07:35 exit status 1
2015/11/20 17:07:36 Generating...
2015/11/20 17:07:36 exit status 1
```

btw, what TYPE does mean? I am adding gitlab paths, but not sure what should be entered into the 'type'.

I believe, that exit1 could be because of SSH keys not picked up? or something like that.

Because If I just do 'git clone ...` from that user - it works perfect.

THank you!

**Comment by benschw** [comment]
sorry, there isn't great error reporting on the satis integration. I've found that the best way to debug these issues is to run the php satis executable directly (targeting the cfg file generated by satis-go.)

Typically, it is a "bad composer format" type error, and in this case its probably from not including "Type"
 (this should be some thing like "svn", "git", or usually "vcs" is sufficient and it can detect the rest.)

**Comment by benschw** [comment]
There should be more verbose errors when the generate job fails now
